airport_mapping = {
    'TPA': 'Tampa International Airport',
    'CLT': 'Charlotte Douglas International Airport',
    'TUL': 'Tulsa International Airport',
    'SEA': 'Seattle-Tacoma International Airport',
    'MEM': 'Memphis International Airport',
    'MKE': 'Milwaukee Mitchell International Airport',
    'MSP': 'Minneapolis-Saint Paul International Airport',
    'ORD': 'Chicago O\'Hare International Airport',
    'ICT': 'Wichita Dwight D. Eisenhower National Airport',
    'LIT': 'Clinton National Airport',
    'DFW': 'Dallas/Fort Worth International Airport',
    'MCI': 'Kansas City International Airport',
    'OMA': 'Eppley Airfield',
    'ABQ': 'Albuquerque International Sunport',
    'BOI': 'Boise Airport',
    'TUS': 'Tucson International Airport',
    'COS': 'Colorado Springs Airport',
    'DEN': 'Denver International Airport',
    'EGE': 'Eagle County Regional Airport',
    'HDN': 'Yampa Valley Airport',
    'JAC': 'Jackson Hole Airport',
    'LAX': 'Los Angeles International Airport',
    'MTJ': 'Montrose Regional Airport',
    'PHX': 'Phoenix Sky Harbor International Airport',
    'EUG': 'Eugene Airport',
    'SLC': 'Salt Lake City International Airport',
    'LAS': 'Harry Reid International Airport',
    'SAN': 'San Diego International Airport',
    'SAT': 'San Antonio International Airport',
    'TYS': 'McGhee Tyson Airport',
    'BWI': 'Baltimore/Washington International Thurgood Marshall Airport',
    'CMH': 'John Glenn Columbus International Airport',
    'DTW': 'Detroit Metropolitan Wayne County Airport',
    'FLL': 'Fort Lauderdale-Hollywood International Airport',
    'MIA': 'Miami International Airport',
    'STL': 'St. Louis Lambert International Airport',
    'VPS': 'Destin-Fort Walton Beach Airport',
    'DAB': 'Daytona Beach International Airport',
    'EYW': 'Key West International Airport',
    'IAH': 'George Bush Intercontinental Airport',
    'JAX': 'Jacksonville International Airport',
    'MCO': 'Orlando International Airport',
    'RSW': 'Southwest Florida International Airport',
    'CVG': 'Cincinnati/Northern Kentucky International Airport',
    'ORF': 'Norfolk International Airport',
    'PNS': 'Pensacola International Airport',
    'SDF': 'Louisville Muhammad Ali International Airport',
    'LEX': 'Blue Grass Airport',
    'IDA': 'Idaho Falls Regional Airport',
    'PSC': 'Tri-Cities Airport',
    'CAK': 'Akron-Canton Airport',
    'LCK': 'Rickenbacker International Airport',
    'CHA': 'Chattanooga Metropolitan Airport',
    'MLI': 'Quad City International Airport',
    'SBN': 'South Bend International Airport',
    'CKB': 'North Central West Virginia Airport',
    'DAY': 'Dayton International Airport',
    'HTS': 'Tri-State Airport',
    'FNT': 'Bishop International Airport',
    'ELM': 'Elmira/Corning Regional Airport',
    'IAG': 'Niagara Falls International Airport',
    'MFR': 'Rogue Valley International-Medford Airport',
    'OWB': 'Owensboro-Daviess County Regional Airport',
    'FSD': 'Sioux Falls Regional Airport',
    'STC': 'St. Cloud Regional Airport',
    'GTF': 'Great Falls International Airport',
    'PGD': 'Punta Gorda Airport',
    'PIE': 'St. Pete-Clearwater International Airport',
    'SFB': 'Orlando Sanford International Airport',
    'RAP': 'Rapid City Regional Airport',
    'TOL': 'Toledo Express Airport',
    'GJT': 'Grand Junction Regional Airport',
    'GRI': 'Central Nebraska Regional Airport',
    'GSO': 'Piedmont Triad International Airport',
    'SGF': 'Springfield-Branson National Airport',
    'LRD': 'Laredo International Airport',
    'MFE': 'McAllen International Airport',
    'MLB': 'Melbourne Orlando International Airport',
    'MRY': 'Monterey Regional Airport',
    'PBG': 'Plattsburgh International Airport',
    'PVU': 'Provo Municipal Airport',
    'ROA': 'Roanoke-Blacksburg Regional Airport',
    'SCK': 'Stockton Metropolitan Airport',
    'SHV': 'Shreveport Regional Airport',
    'SMX': 'Santa Maria Public Airport',
    'TRI': 'Tri-Cities Regional Airport',
    'ITO': 'Hilo International Airport',
    'PPG': 'Pago Pago International Airport',
    'MHT': 'Manchester-Boston Regional Airport',
    'ACV': 'Arcata-Eureka Airport',
    'AZO': 'Kalamazoo/Battle Creek International Airport',
    'BGM': 'Greater Binghamton Airport',
    'HVN': 'Tweed-New Haven Airport',
    'ILM': 'Wilmington International Airport',
    'LAN': 'Capital Region International Airport',
    'PHF': 'Newport News/Williamsburg International Airport',
    'RDD': 'Redding Municipal Airport',
    'SJU': 'Luis Muñoz Marín International Airport',
    'BTR': 'Baton Rouge Metropolitan Airport',
    'LNK': 'Lincoln Airport',
    'PSE': 'Mercedita Airport',
    'BTV': 'Burlington International Airport',
    'GRB': 'Green Bay-Austin Straubel International Airport',
    'FAY': 'Fayetteville Regional Airport',
    'OAJ': 'Albert J. Ellis Airport',
    'CAE': 'Columbia Metropolitan Airport',
    'HSV': 'Huntsville International Airport',
    'CHO': 'Charlottesville-Albemarle Airport',
    'GNV': 'Gainesville Regional Airport',
    'TLH': 'Tallahassee International Airport',
    'HPN': 'Westchester County Airport',
    'WRG': 'Wrangell Airport',
    'ACK': 'Nantucket Memorial Airport',
    'ORH': 'Worcester Regional Airport',
    'MVY': 'Martha\'s Vineyard Airport',
    'BQN': 'Rafael Hernández Airport',
    'RST': 'Rochester International Airport',
    'GPT': 'Gulfport-Biloxi International Airport',
    'MOB': 'Mobile Regional Airport',
    'BFL': 'Meadows Field Airport',
    'AVP': 'Wilkes-Barre/Scranton International Airport',
    'GUC': 'Gunnison-Crested Butte Regional Airport',
    'STT': 'Cyril E. King Airport',
    'HYA': 'Barnstable Municipal Airport',
    'SCE': 'University Park Airport',
    'GUM': 'Antonio B. Won Pat International Airport',
    'STX': 'Henry E. Rohlsen Airport',
    'SBD': 'San Bernardino International Airport',
    'ACY': 'Atlantic City International Airport',
    'CRW': 'Yeager Airport',
    'LBE': 'Arnold Palmer Regional Airport',
    'DLH': 'Duluth International Airport',
    'EAU': 'Chippewa Valley Regional Airport',
    'XWA': 'Williston Basin International Airport',
    'SPN': 'Saipan International Airport',
    'AKN': 'King Salmon Airport',
    'DLG': 'Dillingham Airport',
    'GST': 'Gustavus Airport',
    'BKG': 'Branson Airport',
    'DRO': 'Durango-La Plata County Airport',
    'ILG': 'Wilmington Airport',
    'ITH': 'Ithaca Tompkins Regional Airport',
    'LWS': 'Lewiston-Nez Perce County Regional Airport',
    'OGD': 'Ogden-Hinckley Airport',
    'ADK': 'Adak Airport',
    'ERI': 'Erie International Airport',
    'COD': 'Yellowstone Regional Airport',
    'CPX': 'Benjamin Rivera Noriega Airport',
    'AGS': 'Augusta Regional Airport',
    'FNL': 'Northern Colorado Regional Airport',
    'VQS': 'Antonio Rivera Rodríguez Airport',
    'SUN': 'Friedman Memorial Airport',
    'LCH': 'Lake Charles Regional Airport',
    'BIH': 'Eastern Sierra Regional Airport',
    'DBQ': 'Dubuque Regional Airport',
    'CPR': 'Casper-Natrona County International Airport',
    'VRB': 'Vero Beach Regional Airport',
    'ASE': 'Aspen/Pitkin County Airport',
    'OTH': 'Southwest Oregon Regional Airport',
    'BFM': 'Mobile Downtown Airport',
    'BRO': 'Brownsville/South Padre Island International Airport',
    'SUX': 'Sioux Gateway Airport',
    'HHH': 'Hilton Head Airport',
    'CWA': 'Central Wisconsin Airport',
    'SLE': 'Salem Municipal Airport',
    'JFK': 'John F. Kennedy International Airport',
    'ATL': 'Hartsfield-Jackson Atlanta International Airport'
}


airline_mapping = {
    'AA': 'American Airlines',
    'AS': 'Alaska Airlines',
    'UA': 'United Airlines',
    'WN': 'Southwest Airlines',
    'DL': 'Delta Air Lines',
    'F9': 'Frontier Airlines',
    'G4': 'Allegiant Air',
    'HA': 'Hawaiian Airlines',
    'XP': 'Avelo Airlines',
    'NK': 'Spirit Airlines',
    'B6': 'JetBlue Airways',
    '3M': 'Silver Airways',
    'MX': 'Mexicana de Aviación',
    'SY': 'Sun Country Airlines'
}